spring.application.name=kinedical
spring.data.mongodb.uri=mongodb://localhost:27017/kinedical
spring.data.mongodb.database=kinedical
spring.recommend-api.base-url=http://localhost:8000
server.port=8080

spring.jackson.serialization.write-dates-as-timestamps=false
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web=DEBUG

jwt.secret=YmFzZTY0LWZha2Utc2VjcmV0LWRhdGEtZm9yLWtpbmVkaWNhbA==
jwt.expiration-ms=3600000
